# configuration for "develop" branch
# build in Release mode
-
  environment:
    packageVersion: 1.0.0-dev

  version: '{branch}-%packageVersion%-{build}'
  image: Visual Studio 2017

  nuget:
    project_feed: true

  install:
    - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  cache:
    - packages -> **\packages.config

  pull_requests:
    do_not_increment_build_number: false

  skip_branch_with_pr: false

  before_build:
    - cmd: nuget restore

  after_build:
    - cmd: nuget pack Source\Lib\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.nuspec -OutputDirectory Build\Lib\%CONFIGURATION%\netstandard1.1 -BasePath Source\Lib\%APPVEYOR_PROJECT_NAME% -Properties buildConfig=Release

  build:
    verbosity: minimal

  configuration: Release

  after_test:
    ps: Join-Path "Build\Lib\" -ChildPath $env:CONFIGURATION | Join-Path -ChildPath "\netstandard1.1" | Get-ChildItem | Where-Object {$_.Extension -match '.dll|.pdb|.xml|.nupkg'} | Rename-Item -NewName {'Trakt.NET.' + $env:packageVersion + '-' + $env:APPVEYOR_BUILD_NUMBER + $_.Extension}
    cmd: appveyor PushArtifact Build\Lib\%CONFIGURATION%\netstandard1.1\Trakt.NET.*.nupkg

  branches:
    only:
      - develop

  artifacts:
    - path: Build\Lib\$(CONFIGURATION)\netstandard1.1\Trakt.NET.*.dll
      name: Assembly
    - path: Build\Lib\$(CONFIGURATION)\netstandard1.1\Trakt.NET.*.pdb
      name: AssemblyPDB
    - path: Build\Lib\$(CONFIGURATION)\netstandard1.1\Trakt.NET.*.xml
      name: DocumentationXML
    - path: Build\Lib\$(CONFIGURATION)\netstandard1.1\Trakt.NET.*.nupkg
      name: NugetPackage

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  version: '{branch}-{build}'
  image: Visual Studio 2017

  nuget:
    project_feed: true

  install:
    - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  cache:
    - packages -> **\packages.config

  pull_requests:
    do_not_increment_build_number: false

  skip_branch_with_pr: false

  before_build:
    - cmd: nuget restore

  after_build:
    - cmd: nuget pack Source\Lib\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.nuspec -OutputDirectory Build\Lib\%CONFIGURATION%\netstandard1.1 -BasePath Source\Lib\%APPVEYOR_PROJECT_NAME% -Properties buildConfig=Release

  build:
    verbosity: minimal

  configuration: Release

  after_test:
    ps: Join-Path "Build\Lib\" -ChildPath $env:CONFIGURATION | Join-Path -ChildPath "\netstandard1.1" | Get-ChildItem | Where-Object {$_.Extension -match '.dll|.pdb|.xml|.nupkg'} | Rename-Item -NewName {'Trakt.NET.' + $env:APPVEYOR_BUILD_VERSION + $_.Extension}
    cmd: appveyor PushArtifact Build\Lib\%CONFIGURATION%\netstandard1.1\Trakt.NET.*.nupkg

  artifacts:
    - path: Build\Lib\$(CONFIGURATION)\netstandard1.1\Trakt.NET.*.dll
      name: Assembly
    - path: Build\Lib\$(CONFIGURATION)\netstandard1.1\Trakt.NET.*.pdb
      name: AssemblyPDB
    - path: Build\Lib\$(CONFIGURATION)\netstandard1.1\Trakt.NET.*.xml
      name: DocumentationXML
    - path: Build\Lib\$(CONFIGURATION)\netstandard1.1\Trakt.NET.*.nupkg
      name: NugetPackage
