name: Build

on:
  workflow_call:
    inputs:
      should_run:
        required: true
        type: boolean
      environment_name:
        required: true
        type: string
      target_branch_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      project_name:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      binaries_root_directory:
        required: true
        type: string
      artifacts_root_directory:
        required: true
        type: string
      artifacts_sub_directories:
        required: false
        type: string
      artifacts_archive_name:
        required: true
        type: string
      upload_codecov:
        required: true
        type: boolean
      push_nuget_package:
        required: true
        type: boolean

jobs:
  build:
    if: ${{ inputs.should_run }}
    runs-on: windows-latest
    environment: ${{ inputs.environment_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build environment
        shell: bash
        run: |
          echo "Environment: ${{ inputs.environment_name }}"
          echo "Target Branch Name: ${{ inputs.target_branch_name }}"
          echo "Project Name: ${{ inputs.project_name }}"
          echo "Configuration: ${{ inputs.build_configuration }}"
          echo "Working Directory: ${{ inputs.working_directory }}"
          echo "Binaries Root Directory: ${{ inputs.binaries_root_directory }}"
          echo "Artifacts Root Directory: ${{ inputs.artifacts_root_directory }}"
          echo "Artifacts Sub Directories: ${{ inputs.artifacts_sub_directories }}"
          echo "Artifacts Archive Name: ${{ inputs.artifacts_archive_name }}"
          echo "Push NuGet Packages: ${{ inputs.push_nuget_package }}"
          echo "Upload Codecov reports: ${{ inputs.upload_codecov }}"

      - name: Setup environment variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: './.github/constants.env'  

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: ${{ env.DOTNET_QUALITY }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ inputs.working_directory }}

      - name: Build solution
        run: dotnet build  --configuration ${{ inputs.build_configuration }} --no-restore
        working-directory: ${{ inputs.working_directory }}

      - name: Run tests
        run: dotnet test --configuration ${{ inputs.build_configuration }} --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        working-directory: ${{ inputs.working_directory }}

      - name: Upload coverage reports to Codecov
        if: ${{ inputs.upload_codecov }}
        uses: codecov/codecov-action@v4

      - name: Create NuGet package
        if: ${{ !contains(github.ref, 'pull') && !contains(github.ref, 'epic') && github.actor != 'dependabot[bot]' }}
        run: dotnet pack ${{ inputs.project_name }} --configuration ${{ inputs.build_configuration }} --no-build --no-restore

      - name: Copy binaries to artifacts directory
        if: ${{ !contains(github.ref, 'pull') && !contains(github.ref, 'epic') && github.actor != 'dependabot[bot]' }}
        shell: pwsh
        run: |
          $binariesRootDirectory = "${{ inputs.binaries_root_directory }}/${{ inputs.build_configuration }}"
          $artifactsRootDirectory = "${{ inputs.artifacts_root_directory }}"
          $hasArtifactsSubDirectories = "${{ inputs.artifacts_sub_directories }}" -ne ""
          New-Item -Type Directory -Force $artifactsRootDirectory
          if ($hasArtifactsSubDirectories) {
            $artifactsSubDirectories = "${{ inputs.artifacts_sub_directories }}" -split ","
            foreach ($directory in $artifactsSubDirectories) {
              New-Item -Type Directory -Force "$artifactsRootDirectory/$directory"
            }
            $filePatterns = "Trakt.NET.*.nupkg|Trakt.NET.*.snupkg"
            Get-ChildItem -Path $binariesRootDirectory -Recurse | Where-Object { $_.Fullname -match $filePatterns } | Copy-Item -Destination $artifactsRootDirectory
            $filePatterns = "Trakt.NET*.dll|Trakt.NET*.xml|Trakt.NET*.pdb|Trakt.NET*.deps.json"
            foreach ($directory in $artifactsSubDirectories) {
              Get-ChildItem -Path "$binariesRootDirectory/$directory" -Recurse | Where-Object { $_.Fullname -match $filePatterns } | Copy-Item -Destination "$artifactsRootDirectory/$directory"
            }
          } else {
            $filePatterns = "Trakt.NET*.dll|Trakt.NET*.xml|Trakt.NET*.pdb|Trakt.NET*.deps.json|Trakt.NET.*.nupkg|Trakt.NET.*.snupkg"
            Get-ChildItem -Path $binariesRootDirectory -Recurse | Where-Object { $_.Fullname -match $filePatterns } | Copy-Item -Destination $artifactsRootDirectory
          }

      - name: Upload artifacts
        if: ${{ !contains(github.ref, 'pull') && !contains(github.ref, 'epic') && github.actor != 'dependabot[bot]' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifacts_archive_name }}-${{ github.run_number }}-${{ github.sha }}
          retention-days: 14
          path: '${{ inputs.artifacts_root_directory }}/'

      - name: Push NuGet package to Github Package Registry
        if: ${{ inputs.push_nuget_package && !contains(github.ref, 'pull') && !contains(github.ref, 'epic') && github.actor != 'dependabot[bot]' }}
        run: dotnet nuget push '**/Trakt.NET*.nupkg' --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/henrikfroehling --skip-duplicate
        working-directory: ${{ inputs.working_directory }}
  
      - name: Push package to NuGet
        if: ${{ inputs.push_nuget_package && startsWith(github.ref, 'refs/tags/v') }}
        run: dotnet nuget push '**/Trakt.NET*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
