name: "Code Scan"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'Postman/**'
      - 'AUTHORS.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'Changelog.md'
      - 'LICENSE.md'
      - 'PublishRelease.txt'
      - 'README.md'
      - 'coding_style.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'Postman/**'
      - 'AUTHORS.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'Changelog.md'
      - 'LICENSE.md'
      - 'PublishRelease.txt'
      - 'README.md'
      - 'coding_style.md'
      - 'docs/**'

jobs:
  codeql:
    name: "Code-QL"
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      Project_Name: 'Source/Lib/Trakt.NET/Trakt.NET.csproj'

    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']
        configuration: [Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'csharp'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'Source'

    - name: Build solution
      run: dotnet build  --configuration Release --no-restore
      working-directory: 'Source'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
