name: Dependabot auto-approve

on: pull_request

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  dependabot-auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    env:
      GH_TOKEN: ${{ secrets.PR_APPROVAL }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve Dependabot PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PR_APPROVAL }}
